"""empty message

Revision ID: 0808f8c95746
Revises: 427f3a304a78
Create Date: 2017-10-26 14:53:46.004586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0808f8c95746'
down_revision = '427f3a304a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'test')
    # ### end Alembic commands ###
