"""empty message

Revision ID: 2193cc00775f
Revises: 
Create Date: 2017-10-24 00:19:54.939980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2193cc00775f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('caseID', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('caseID')
    )
    op.create_table('numbers',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('number', sa.TEXT(), nullable=True),
    sa.Column('onCampus', sa.INTEGER(), nullable=True),
    sa.Column('allDay', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('bb-case-tracking',
    sa.Column('requestID', sa.INTEGER(), nullable=False),
    sa.Column('caseID', sa.INTEGER(), nullable=False),
    sa.Column('deviceID', sa.TEXT(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['caseID'], ['case.caseID'], ),
    sa.PrimaryKeyConstraint('requestID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bb-case-tracking')
    op.drop_table('numbers')
    op.drop_table('case')
    # ### end Alembic commands ###
