"""empty message

Revision ID: 427f3a304a78
Revises: 61b6204589bc
Create Date: 2017-10-25 23:54:45.535220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '427f3a304a78'
down_revision = '61b6204589bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb-case-tracking', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('bb-case-tracking', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bb-case-tracking', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('bb-case-tracking', 'timestamp')
    # ### end Alembic commands ###
