"""empty message

Revision ID: 44dc929bff07
Revises: 
Create Date: 2018-04-12 19:08:11.303537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44dc929bff07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('numbers',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('on_campus', sa.Integer(), nullable=True),
    sa.Column('all_day', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('bb-case-tracking',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.case_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.drop_table('course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'course_pkey')
    )
    op.drop_table('bb-case-tracking')
    op.drop_table('numbers')
    op.drop_table('case')
    # ### end Alembic commands ###
