"""empty message

Revision ID: 61b6204589bc
Revises: 
Create Date: 2017-10-24 15:32:53.859929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b6204589bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('numbers',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('number', sa.Text(), nullable=True),
    sa.Column('on_campus', sa.Integer(), nullable=True),
    sa.Column('all_day', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('bb-case-tracking',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.case_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bb-case-tracking')
    op.drop_table('numbers')
    op.drop_table('case')
    # ### end Alembic commands ###
