"""empty message

Revision ID: 91937cb1e3e9
Revises: c632754a94b2
Create Date: 2018-05-22 00:05:09.350963

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91937cb1e3e9'
down_revision = 'c632754a94b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.case_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.drop_table('bb-case-tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bb-case-tracking',
    sa.Column('request_id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"bb-case-tracking_request_id_seq1"\'::regclass)'), nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], [u'case.case_id'], name=u'bb-case-tracking_case_id_fkey1'),
    sa.PrimaryKeyConstraint('request_id', name=u'bb-case-tracking_pkey1')
    )
    op.drop_table('request')
    # ### end Alembic commands ###
